# Generated by Django 3.1.3 on 2021-06-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('reg_no', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('sex', models.CharField(choices=[('CS', 'Choose sex'), ('M', 'male'), ('F', 'female')], default='CS', max_length=5)),
                ('status', models.CharField(choices=[('CS', 'Choose Status'), ('UG', 'undergraduate'), ('PG', 'postgraduate')], default='CS', max_length=20)),
            ],
        ),
    ]
